server:
  port: 8039
servername:
  apiServer
spring:
  session:
    store-type: none
  main:
    allow-bean-definition-overriding: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ry?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: MIma112233!!!!

## Mybatis 配置
mybatis:
  mapperLcations: classpath:com/magic/ruoyiapi/mapper/*.xml
  typeAliasesPackage: com.magic.ruoyiapi.entity
logging:
  level:
    com.magic : INFO
redis:
  host: 127.0.0.1
  port: 6379
  password:
  timeout: 3000
  pool:
    maxTotal: 8
    maxIdle: 8
    minIdle: 4
  database: 5
  key:
    prefix: market
  uri:  redis://:${redis.password}@${redis.host}:${redis.port}/0
